# Generated by Django 2.1.2 on 2018-11-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoafisica',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='cep',
            field=models.CharField(max_length=9),
        ),
    ]
