# Generated by Django 2.1.2 on 2018-11-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181110_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_pf',
            field=models.BooleanField(default=False, verbose_name='Pessoa física'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_pj',
            field=models.BooleanField(default=False, verbose_name='Pessoa jurídica'),
        ),
    ]
