# Generated by Django 2.0.10 on 2019-04-11 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituicoes', '0002_instituicaolista_user_inst'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandaDoacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doacao', models.CharField(max_length=200)),
                ('qtd', models.IntegerField(default=1)),
                ('obs', models.TextField(blank=True, null=True)),
                ('recebido', models.BooleanField(default=False)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('dt_atualizacao', models.DateTimeField(auto_now=True)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='instituicoes.InstituicaoLista')),
            ],
        ),
    ]
