# Generated by Django 2.0.10 on 2019-05-04 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandaDoacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doacao', models.CharField(max_length=200)),
                ('qtd', models.IntegerField(default=1)),
                ('obs', models.TextField(blank=True, null=True)),
                ('recebido', models.BooleanField(default=False)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('dt_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoacaoOutros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=30)),
                ('tipo_doacao', models.CharField(choices=[('MONEY', 'Dinheiro'), ('PRODUCTS', 'Produtos'), ('SERVICES', 'Serviços')], max_length=8)),
                ('doacao', models.CharField(max_length=300)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('dt_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoacaoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('dt_atualizacao', models.DateTimeField(auto_now=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doacoes.DemandaDoacao')),
            ],
        ),
    ]
