# Generated by Django 2.0.10 on 2019-04-22 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instituicoes', '0002_instituicaolista_user_inst'),
        ('doacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoacaoOutros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doacao', models.CharField(choices=[('MONEY', 'Dinheiro'), ('PRODUCTS', 'Produtos'), ('SERVICES', 'Serviços')], max_length=8)),
                ('doacao', models.CharField(max_length=300)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('dt_atualizacao', models.DateTimeField(auto_now=True)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='instituicoes.InstituicaoLista')),
            ],
        ),
    ]
