# Generated by Django 2.0.10 on 2019-05-18 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0002_auto_20190504_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandadoacao',
            name='qtd',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
