# Generated by Django 2.0.10 on 2019-05-01 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doacoes', '0002_doacaooutros'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoacaoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('dt_atualizacao', models.DateTimeField(auto_now=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doacoes.DemandaDoacao')),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
