# Generated by Django 2.1.2 on 2018-11-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoajurica',
            name='is_instituicao',
            field=models.BooleanField(default=False),
        ),
    ]
