# Generated by Django 2.1.2 on 2018-11-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicaolista',
            name='descricao',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
