# Generated by Django 2.1.2 on 2018-11-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicaolista',
            name='autorizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instituicaolista',
            name='editado',
            field=models.BooleanField(default=False),
        ),
    ]
